In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import LabelEncoder

In [48]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [49]:
#Data cleaning
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [50]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [45]:
#data cleaning
#dont run
def age_convert(c):
    age=c[0]
    pclass=c[1]
    if pd.isnull(age):
        if pclass==1:
            return 38
        elif pclass==2:
            return 29
        else:
            return 25
    else:
        return age

In [46]:
#train['Age']=train[['Age','Pclass']].apply(age_convert,axis=1)

In [10]:
#test['Age']=test[['Age','Pclass']].apply(age_convert,axis=1)

In [51]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [52]:
train.drop(['Name','Ticket', 'Cabin','Embarked'],axis=1,inplace=True)

In [53]:
test.drop(['Name','Ticket','Cabin','Embarked'],axis=1,inplace=True)

In [54]:
train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0            1         0       3    male  22.0      1      0   7.2500
1            2         1       1  female  38.0      1      0  71.2833
2            3         1       3  female  26.0      0      0   7.9250
3            4         1       1  female  35.0      1      0  53.1000
4            5         0       3    male  35.0      0      0   8.0500

In [55]:
test.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare
0          892       3    male  34.5      0      0   7.8292
1          893       3  female  47.0      1      0   7.0000
2          894       2    male  62.0      0      0   9.6875
3          895       3    male  27.0      0      0   8.6625
4          896       3  female  22.0      1      1  12.2875

In [56]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
dtype: int64

In [57]:
train.fillna(train.mean(),inplace=True)
test.fillna(test.mean(),inplace=True)


PassengerId  Pclass     Sex       Age  SibSp  Parch      Fare
0            892       3    male  34.50000      0      0    7.8292
1            893       3  female  47.00000      1      0    7.0000
2            894       2    male  62.00000      0      0    9.6875
3            895       3    male  27.00000      0      0    8.6625
4            896       3  female  22.00000      1      1   12.2875
5            897       3    male  14.00000      0      0    9.2250
6            898       3  female  30.00000      0      0    7.6292
7            899       2    male  26.00000      1      1   29.0000
8            900       3  female  18.00000      0      0    7.2292
9            901       3    male  21.00000      2      0   24.1500
10           902       3    male  30.27259      0      0    7.8958
11           903       1    male  46.00000      0      0   26.0000
12           904       1  female  23.00000      1      0   82.2667
13           905       2    male  63.00000      1      0   26.0000
14           906       1  female  47.00000      1      0   61.1750
15           907       2  female  24.00000      1      0   27.7208
16           908       2    male  35.00000      0      0   12.3500
17           909       3    male  21.00000      0      0    7.2250
18           910       3  female  27.00000      1      0    7.9250
19           911       3  female  45.00000      0      0    7.2250
20           912       1    male  55.00000      1      0   59.4000
21           913       3    male   9.00000      0      1    3.1708
22           914       1  female  30.27259      0      0   31.6833
23           915       1    male  21.00000      0      1   61.3792
24           916       1  female  48.00000      1      3  262.3750
25           917       3    male  50.00000      1      0   14.5000
26           918       1  female  22.00000      0      1   61.9792
27           919       3    male  22.50000      0      0    7.2250
28           920       1    male  41.00000      0      0   30.5000
29           921       3    male  30.27259      2      0   21.6792
..           ...     ...     ...       ...    ...    ...       ...
388         1280       3    male  21.00000      0      0    7.7500
389         1281       3    male   6.00000      3      1   21.0750
390         1282       1    male  23.00000      0      0   93.5000
391         1283       1  female  51.00000      0      1   39.4000
392         1284       3    male  13.00000      0      2   20.2500
393         1285       2    male  47.00000      0      0   10.5000
394         1286       3    male  29.00000      3      1   22.0250
395         1287       1  female  18.00000      1      0   60.0000
396         1288       3    male  24.00000      0      0    7.2500
397         1289       1  female  48.00000      1      1   79.2000
398         1290       3    male  22.00000      0      0    7.7750
399         1291       3    male  31.00000      0      0    7.7333
400         1292       1  female  30.00000      0      0  164.8667
401         1293       2    male  38.00000      1      0   21.0000
402         1294       1  female  22.00000      0      1   59.4000
403         1295       1    male  17.00000      0      0   47.1000
404         1296       1    male  43.00000      1      0   27.7208
405         1297       2    male  20.00000      0      0   13.8625
406         1298       2    male  23.00000      1      0   10.5000
407         1299       1    male  50.00000      1      1  211.5000
408         1300       3  female  30.27259      0      0    7.7208
409         1301       3  female   3.00000      1      1   13.7750
410         1302       3  female  30.27259      0      0    7.7500
411         1303       1  female  37.00000      1      0   90.0000
412         1304       3  female  28.00000      0      0    7.7750
413         1305       3    male  30.27259      0      0    8.0500
414         1306       1  female  39.00000      0      0  108.9000
415         1307       3    male  38.50000      0   

In [58]:
train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
dtype: int64

In [59]:
test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
dtype: int64

In [60]:
#survival count wrt Pclass
train.groupby('Pclass')['Survived'].value_counts()

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: Survived, dtype: int64

In [61]:

,as_index=True).mean().sort_values(by='Survived',ascending=True)

NameError: name 'as_index' is not defined

In [62]:
a=train[['Sex','Survived']].groupby('Sex')
a

In [63]:
labelEncoder=LabelEncoder()
labelEncoder.fit(train['Sex'])
labelEncoder.fit(test['Sex'])
train['Sex']=labelEncoder.transform(train['Sex'])
test['Sex']=labelEncoder.transform(test['Sex'])


In [66]:
x=np.array(train.drop(['Survived'],1).astype(float))
y=np.array(train['Survived'])


In [67]:
from sklearn.cluster import KMeans
model=KMeans(n_clusters=2)# we want cluster for whether survived or not

In [68]:
model.fit(x)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [70]:
correct=0
for i in range(len(x)):
    predict_me=np.array(x[i].astype(float))
    #print(predict_me)
    predict_me=predict_me.reshape(-1,len(predict_me))
    #print(predict_me)
    prediction=model.predict(predict_me)
    if prediction[0] == y[i]:
        correct +=1
print(correct/len(x))        
        

[  1.     3.     1.    22.     1.     0.     7.25]
[[  1.     3.     1.    22.     1.     0.     7.25]]
[  2.       1.       0.      38.       1.       0.      71.2833]
[[  2.       1.       0.      38.       1.       0.      71.2833]]
[  3.      3.      0.     26.      0.      0.      7.925]
[[  3.      3.      0.     26.      0.      0.      7.925]]
[  4.    1.    0.   35.    1.    0.   53.1]
[[  4.    1.    0.   35.    1.    0.   53.1]]
[  5.     3.     1.    35.     0.     0.     8.05]
[[  5.     3.     1.    35.     0.     0.     8.05]]
[  6.           3.           1.          29.69911765   0.           0.
   8.4583    ]
[[  6.           3.           1.          29.69911765   0.           0.
    8.4583    ]]
[  7.       1.       1.      54.       0.       0.      51.8625]
[[  7.       1.       1.      54.       0.       0.      51.8625]]
[  8.      3.      1.      2.      3.      1.     21.075]
[[  8.      3.      1.      2.      3.      1.     21.075]]
[  9.       3.       0.    

[ 273.     2.     0.    41.     0.     1.    19.5]
[[ 273.     2.     0.    41.     0.     1.    19.5]]
[ 274.     1.     1.    37.     0.     1.    29.7]
[[ 274.     1.     1.    37.     0.     1.    29.7]]
[ 275.            3.            0.           29.69911765    0.            0.
    7.75      ]
[[ 275.            3.            0.           29.69911765    0.            0.
     7.75      ]]
[ 276.        1.        0.       63.        1.        0.       77.9583]
[[ 276.        1.        0.       63.        1.        0.       77.9583]]
[ 277.      3.      0.     45.      0.      0.      7.75]
[[ 277.      3.      0.     45.      0.      0.      7.75]]
[ 278.            2.            1.           29.69911765    0.            0.
    0.        ]
[[ 278.            2.            1.           29.69911765    0.            0.
     0.        ]]
[ 279.       3.       1.       7.       4.       1.      29.125]
[[ 279.       3.       1.       7.       4.       1.      29.125]]
[ 280.      3.    